name: project_z
description: survey zulu

version: 2.1.0+8

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  charts_flutter: ^0.7.0
  contacts_service: ^0.3.4
  cupertino_icons: ^0.1.2
  equatable: ^0.4.0
  flutter_bloc: ^0.21.0
  flutter_facebook_login: ^3.0.0
  flutter_form_builder: ^3.4.1
  google_sign_in: ^4.0.7
  http: ^0.12.0+2
  image_picker: ^0.6.1+4
  in_app_purchase: ^0.2.1+3
  local_auth: ^0.5.2+4
  native_widgets: ^1.3.2
  rxdart: ^0.22.1+1
  shared_preferences: ^0.5.3+4
  url_launcher: ^5.1.3


#   flutter_launcher_icons: ^0.7.2+1

# flutter_icons:
#   image_path: assets/images/icon.png
#   android: true
#   ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
    - assets/images/icon.png
    - assets/images/splashLogo.png
    - assets/images/zulu.png
    - assets/images/zulu.svg
    - assets/icons/
    - assets/icons/loginWithFacebook.png
    - assets/icons/loginWithGoogle.png
    - assets/files/question_types_list.json
