name: project_z
description: survey zulu

version: 2.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  native_widgets: ^1.3.2
  shared_preferences: ^0.5.3+4
  local_auth: ^0.5.2+4
  http: ^0.12.0+2
  flutter_bloc: ^0.21.0
  equatable: ^0.4.0
  rxdart: ^0.22.1+1
  charts_flutter: ^0.7.0
  flutter_form_builder: ^3.4.1
  google_sign_in: ^4.0.6
  flutter_facebook_login: ^2.0.1
  cupertino_icons: ^0.1.2


#   flutter_launcher_icons: ^0.7.2+1

# flutter_icons:
#   image_path: assets/images/icon.png
#   android: true
#   ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
    - assets/images/icon.png
    - assets/images/splashLogo.png
    - assets/images/zulu.png
    - assets/images/zulu.svg
    - assets/icons/
    - assets/icons/loginWithFacebook.png
    - assets/icons/loginWithGoogle.png
    - assets/files/question_types_list.json
